<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>WarehouseManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WarehouseManagement.Application.Contracts\WarehouseManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\src\WarehouseManagement.Application\WarehouseManagement.Application.csproj" />
    <ProjectReference Include="..\WarehouseManagement.Domain.Tests\WarehouseManagement.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="Moq" Version="4.18.4" />
  </ItemGroup>

</Project>
