<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
	<RootNamespace>Wcs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetEscapades.Configuration.Yaml" Version="3.1.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="6.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.26" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.17" />
    <PackageReference Include="Volo.Abp.Core" Version="6.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="110.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="LogTool\" />
  </ItemGroup>

</Project>
