<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net6.0</TargetFramework>
	  <RootNamespace>Ecs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac" Version="6.0.3" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="6.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecs.Application\Ecs.Application.csproj" />
    <ProjectReference Include="..\Ecs.BackgroundJob\Ecs.BackGroundJob.csproj" />
    <ProjectReference Include="..\Ecs.EntityFrameworkCore\Ecs.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Ecs.HttpApi\Ecs.HttpApi.csproj" />
  </ItemGroup>

</Project>
