<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>WarehouseManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EntityFrameworkCore\AllocWall\**" />
    <EmbeddedResource Remove="EntityFrameworkCore\AllocWall\**" />
    <None Remove="EntityFrameworkCore\AllocWall\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="5.1.3" />
    <ProjectReference Include="..\WarehouseManagement.Domain\WarehouseManagement.Domain.csproj" />
  </ItemGroup>

</Project>
