<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcServer.Cache\PlcServer.Cache.csproj" />
    <ProjectReference Include="..\PlcServer.Defines\PlcServer.Defines.csproj" />
    <ProjectReference Include="..\PlcServer.Driver.Base\PlcServer.Driver.Base.csproj" />
  </ItemGroup>

</Project>
