// <auto-generated />
using System;
using Wcs.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Wcs.Migrations
{
    [DbContext(typeof(WcsDbContext))]
    partial class WcsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.Sqlite)
                .HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("Wcs.Caches.Models.DispatchCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CachePos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskIdOwnIt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchcaches");
                });

            modelBuilder.Entity("Wcs.Cells.Models.DispatchCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CellName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CellSpecs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Col")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColNoInSectForPlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Layer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayerForPlc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativeNode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowForPlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectNoForPlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchcells");
                });

            modelBuilder.Entity("Wcs.Cells.Models.DispatchWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchwarehouses");
                });

            modelBuilder.Entity("Wcs.Conditions.Models.DispatchCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionSrc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Describe")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchconditions");
                });

            modelBuilder.Entity("Wcs.DahSpecss.Models.DahSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dahspecs");
                });

            modelBuilder.Entity("Wcs.Jobs.Models.DispatchJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateTime")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobCmdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextFalseStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextTrueStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchjobs");
                });

            modelBuilder.Entity("Wcs.Jobs.Models.DispatchJobCmd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Describe")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCmdClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchjobcmds");
                });

            modelBuilder.Entity("Wcs.Jobs.Models.DispatchJobId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchjobids");
                });

            modelBuilder.Entity("Wcs.Jobs.Models.DispatchJobWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Describe")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobWorkerClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchjobworkers");
                });

            modelBuilder.Entity("Wcs.Nodes.Models.DispatchNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmdTagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DASpecs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseTagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskIdOwnIt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchnodes");
                });

            modelBuilder.Entity("Wcs.Nodes.Models.DispatchNodeCmd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeCmdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeCmdValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchnodecmds");
                });

            modelBuilder.Entity("Wcs.Nodes.Models.DispatchNodeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Describe")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchnodetypes");
                });

            modelBuilder.Entity("Wcs.Orders.Models.DispatchChkOrderRslt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchchkorderrslts");
                });

            modelBuilder.Entity("Wcs.Orders.Models.DispatchOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanOpenDoorImmediate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateTime")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndNode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecInfo")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecStep")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecUpdateTime")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasError")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LastCheckOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateSpecs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartNode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchorders");
                });

            modelBuilder.Entity("Wcs.Processes.Models.DispatchProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndNodeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartNodeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("dispatchprocesses");
                });

            modelBuilder.Entity("Wcs.Processes.Models.DispatchProcessStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Describe")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobCmdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextFalseStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextTrueStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchprocesssteps");
                });

            modelBuilder.Entity("Wcs.Processes.Models.DispatchProcessStepPrecondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Describe")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchprocesssteppreconditions");
                });

            modelBuilder.Entity("Wcs.Processes.Models.DispatchProcessStepResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchprocessstepresources");
                });

            modelBuilder.Entity("Wcs.Tasks.Models.DispatchTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachePos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateTime")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndNode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastChkOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartNode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchtasks");
                });

            modelBuilder.Entity("Wcs.Tasks.Models.DispatchTaskId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dispatchtaskids");
                });
#pragma warning restore 612, 618
        }
    }
}
