<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net6.0</TargetFramework>
	  <RootNamespace>Ecs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Localization" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Localization\Ecs\" />
  </ItemGroup>

</Project>
