<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../humanoid-archive-wms/modules/WarehouseManagement/src/WarehouseManagement.Domain/WarehouseManagement.Domain.csproj" />
  </ItemGroup>
</Project>
