<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="App.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcServer.Core\PlcServer.Core.csproj" />
    <ProjectReference Include="..\PlcServer.Driver.Siemens\PlcServer.Driver.Siemens.csproj" />
    <ProjectReference Include="..\PlcServer.Driver.Simulation\PlcServer.Driver.Simulation.csproj" />
    <ProjectReference Include="..\PlcServer.Jobs\PlcServer.Jobs.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
