<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wcs.Application.Contracts\Wcs.Application.Contracts.csproj" />
    <ProjectReference Include="..\Wcs.Domain.Shared\Wcs.Domain.Shared.csproj" />
    <ProjectReference Include="..\Wcs.Domain\Wcs.Domain.csproj" />
    <ProjectReference Include="..\Wcs.Tools\Wcs.Tools.csproj" />
  </ItemGroup>

</Project>
