<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { CircleCheck, CircleClose, Loading, Menu, Monitor, Operation, Refresh, Tickets, VideoPause, VideoPlay } from '@element-plus/icons-vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import { changeWcsState, runTest } from './api/wcs';
import { useWcsStore } from './stores/wcs';

const { t } = useI18n(); const router = useRouter(); const route = useRoute(); const wcs = useWcsStore(); const drawerOpen = ref(false); const actionLoading = ref<string | null>(null); const actionResult = ref<Record<string, 'success' | 'error'>>({});
const stateText = computed(() => t(`state.${wcs.state}`));
const connectionText = computed(() => ({ connected: '实时连接已连接', reconnecting: '实时连接重连中', disconnected: '实时连接已断开', failed: '实时连接失败' }[wcs.connectionStatus] || '实时连接状态未知'));
const connectionTagType = computed(() => ({ connected: 'success', reconnecting: 'warning', disconnected: 'info', failed: 'danger' }[wcs.connectionStatus] || 'info'));
const navItems = computed(() => [{ path:'/orders', label:t('menu.orders'), icon:Tickets }, { path:'/tags', label:t('menu.tags'), icon:Monitor }, { path:'/logs', label:t('menu.logs'), icon:Operation }]);
function navigate(path:string) { drawerOpen.value = false; router.push(path); }
function clearActionResult(action: string) { window.setTimeout(() => { delete actionResult.value[action]; }, 1800); }
function actionIcon(action: string) { if (actionLoading.value === action) return Loading; if (actionResult.value[action] === 'success') return CircleCheck; if (actionResult.value[action] === 'error') return CircleClose; return action === 'state' ? (wcs.state === 'Running' ? VideoPause : VideoPlay) : action === 'restart' ? Refresh : action === 'stop' ? VideoPause : VideoPlay; }
async function stateAction() { const action = 'state'; actionLoading.value = action; delete actionResult.value[action]; try { const result = await changeWcsState(wcs.state === 'Running' ? 'pause' : 'restart'); if (!result.success) { actionResult.value[action] = 'error'; ElMessage.error(result.message); } else { actionResult.value[action] = 'success'; wcs.state = wcs.state === 'Running' ? 'Pause' : 'Running'; } } finally { actionLoading.value = null; clearActionResult(action); } }
async function testAction(action:'start'|'stop'|'restart') { actionLoading.value = action; delete actionResult.value[action]; try { const result = await runTest(action); if (result.success) { actionResult.value[action] = 'success'; ElMessage.success(result.message || '操作已提交'); } else { actionResult.value[action] = 'error'; ElMessage.error(result.message); } } finally { actionLoading.value = null; clearActionResult(action); } }
onMounted(() => wcs.initialize().catch(() => ElMessage.error('WCS 服务连接失败')));
</script>
<template>
  <el-container class="app-shell">
    <el-aside class="desktop-aside" width="236px"><div class="brand"><div class="brand-mark"><el-icon><VideoPlay /></el-icon></div><div><strong>RenXing WCS</strong><span>档案库调度监控</span></div></div><nav class="side-nav"><button v-for="item in navItems" :key="item.path" class="nav-item" :class="{active:route.path.startsWith(item.path)}" @click="navigate(item.path)"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span></button></nav></el-aside>
    <el-container><el-header class="topbar"><div class="topbar-left"><el-button class="menu-button" circle @click="drawerOpen=true"><el-icon><Menu /></el-icon></el-button><div><div class="eyebrow">WAREHOUSE CONTROL SYSTEM</div><h1>{{ navItems.find(item => route.path.startsWith(item.path))?.label || 'WCS Monitor' }}</h1></div></div><div class="topbar-actions"><el-tag class="connection-tag" :type="connectionTagType" effect="light">{{ connectionText }}</el-tag><el-tag class="state-pill" :type="wcs.state==='Running'?'success':wcs.state==='Pause'?'warning':'info'" effect="light">{{ stateText }}</el-tag><el-button class="state-button" :icon="actionIcon('state')" :loading="actionLoading==='state'" :type="wcs.state==='Running'?'warning':'success'" @click="stateAction">{{ wcs.state==='Running'?'暂停服务':'恢复服务' }}</el-button></div></el-header>
      <el-main class="main-content"><div class="quick-actions content-card"><div><span class="eyebrow">CONTROL CENTER</span><strong>调度控制</strong></div><el-space wrap><el-button :icon="actionIcon('start')" :loading="actionLoading==='start'" @click="testAction('start')">启动测试</el-button><el-button :icon="actionIcon('stop')" :loading="actionLoading==='stop'" @click="testAction('stop')">停止测试</el-button><el-button :icon="actionIcon('restart')" :loading="actionLoading==='restart'" @click="testAction('restart')">重启测试</el-button></el-space></div><Transition name="page" mode="out-in"><router-view /></Transition></el-main></el-container>
    <el-drawer v-model="drawerOpen" title="RenXing WCS" direction="ltr" size="82%"><nav class="mobile-nav"><button v-for="item in navItems" :key="item.path" class="nav-item" :class="{active:route.path.startsWith(item.path)}" @click="navigate(item.path)"><el-icon><component :is="item.icon" /></el-icon>{{ item.label }}</button></nav></el-drawer>
  </el-container>
</template>
<style scoped>
.app-shell{min-height:100vh;background:var(--wcs-page)} .desktop-aside{position:relative;display:flex;flex-direction:column;padding:28px 16px 20px;background:#14213d;color:#fff}.brand{display:flex;align-items:center;gap:11px;padding:0 10px 34px}.brand-mark{display:grid;width:38px;height:38px;place-items:center;border-radius:12px;background:linear-gradient(135deg,#60a5fa,#2563eb);font-size:21px}.brand strong,.brand span{display:block}.brand strong{font-size:15px}.brand span{margin-top:4px;color:#9fb1d2;font-size:11px}.side-nav,.mobile-nav{display:grid;gap:7px}.nav-item{display:flex;align-items:center;gap:12px;width:100%;padding:12px 14px;border:0;border-radius:11px;background:transparent;color:#aebbd3;cursor:pointer;font-weight:600;text-align:left;transition:all .2s ease}.nav-item:hover,.nav-item.active{background:rgba(96,165,250,.16);color:#fff}.nav-item.active{box-shadow:inset 3px 0 #60a5fa}.aside-footer{display:flex;align-items:center;gap:8px;margin-top:auto;padding:14px 10px 0;border-top:1px solid rgba(255,255,255,.1);color:#9fb1d2;font-size:12px}.connection-dot{width:8px;height:8px;border-radius:50%;background:#f87171}.connection-dot.online{background:#34d399;box-shadow:0 0 0 4px rgba(52,211,153,.15)}.topbar{display:flex;align-items:center;justify-content:space-between;height:82px;padding:0 32px;background:rgba(255,255,255,.86);border-bottom:1px solid var(--wcs-border);backdrop-filter:blur(14px)}.topbar-left,.topbar-actions{display:flex;align-items:center;gap:14px}.topbar h1{margin:3px 0 0;font-size:20px}.eyebrow{color:var(--wcs-muted);font-size:10px;font-weight:800;letter-spacing:.12em}.menu-button{display:none}.state-pill{padding:0 11px;border-radius:999px}.state-button{min-width:102px}.main-content{max-width:1500px;width:100%;margin:0 auto;padding:26px 32px 40px}.quick-actions{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:26px;padding:16px 20px}.quick-actions strong{display:block;margin-top:4px;font-size:15px}.page-enter-active,.page-leave-active{transition:opacity .18s ease,transform .18s ease}.page-enter-from{opacity:0;transform:translateY(8px)}.page-leave-to{opacity:0;transform:translateY(-4px)}
@media(max-width:768px){.desktop-aside{display:none}.topbar{height:auto;min-height:72px;padding:14px 16px}.menu-button{display:inline-flex}.topbar-actions{gap:8px}.state-pill{display:none}.state-button{min-width:0;padding:8px 11px}.main-content{padding:16px 14px 28px}.quick-actions{align-items:flex-start;flex-direction:column;margin-bottom:18px;padding:15px}.quick-actions .el-space{width:100%}.quick-actions .el-button{flex:1;min-width:100px}}
</style>
