<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { ElMessage } from 'element-plus'; import { getMjjTags, getPlcTags } from '../api/wcs'; import { hubConnection, startHub } from '../services/signalr'; import type { MjjTag, PlcTag } from '../types/wcs';
const plcTags = ref<PlcTag[]>([]); const mjjTags = ref<MjjTag[]>([]); const plcSort = ref<'monitorTagName'|'monitorTagAddr'|'monitorTagValue'>('monitorTagName'); const mjjSort = ref<'tagName'|'tagValue'>('tagName'); const order = ref<'ascending'|'descending'>('ascending');
const sortedPlcTags = computed(() => [...plcTags.value].sort((a,b) => String(a[plcSort.value]).localeCompare(String(b[plcSort.value]), 'zh-CN', {numeric:true}) * (order.value === 'ascending' ? 1 : -1))); const sortedMjjTags = computed(() => [...mjjTags.value].sort((a,b) => String(a[mjjSort.value]).localeCompare(String(b[mjjSort.value]), 'zh-CN', {numeric:true}) * (order.value === 'ascending' ? 1 : -1)));
const updatePlc = (data: PlcTag[]) => { plcTags.value = data; }; const updateMjj = (data: MjjTag[]) => { mjjTags.value = data; }; function plcSortChange({prop, order:next}:{prop:'monitorTagName'|'monitorTagAddr'|'monitorTagValue';order:'ascending'|'descending'|null}) { if(next){plcSort.value=prop;order.value=next;} } function mjjSortChange({prop, order:next}:{prop:'tagName'|'tagValue';order:'ascending'|'descending'|null}) { if(next){mjjSort.value=prop;order.value=next;} }
onMounted(async () => { try { [plcTags.value, mjjTags.value] = await Promise.all([getPlcTags(), getMjjTags()]); await startHub(); hubConnection.on('UpdatePlcTags', updatePlc); hubConnection.on('UpdateMjjStatus', updateMjj); } catch { ElMessage.error('点位数据加载失败'); } }); onUnmounted(() => { hubConnection.off('UpdatePlcTags', updatePlc); hubConnection.off('UpdateMjjStatus', updateMjj); });
</script>
<template><section class="page-view"><div class="page-heading"><div><h1>点位监控</h1></div></div><el-row :gutter="20"><el-col :xs="24" :sm="24" :md="14"><div class="content-card monitor-card"><h2>PLC 点位</h2><el-table :data="sortedPlcTags" border @sort-change="plcSortChange"><el-table-column prop="monitorTagName" label="变量名称" sortable="custom" min-width="150"/><el-table-column prop="monitorTagAddr" label="变量地址" sortable="custom" min-width="150"/><el-table-column prop="monitorTagValue" label="变量值" sortable="custom" min-width="120"/></el-table></div></el-col><el-col :xs="24" :sm="24" :md="10"><div class="content-card monitor-card"><h2>密集架点位</h2><el-table :data="sortedMjjTags" border @sort-change="mjjSortChange"><el-table-column prop="tagName" label="变量名称" sortable="custom" min-width="180"/><el-table-column prop="tagValue" label="变量值" sortable="custom" min-width="120"/></el-table></div></el-col></el-row></section></template>
<style scoped>.monitor-card{padding:18px}.monitor-card h2{margin:0 0 16px;font-size:17px}@media(max-width:768px){.monitor-card{margin-bottom:16px}}</style>
